In [39]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
import pickle

In [40]:
data=pd.read_csv("Churn_Modelling.csv")

In [41]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [42]:
data=data.drop(columns=["RowNumber","CustomerId","Surname"],axis=1,inplace=False)

In [43]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [44]:
## Encode categorical variables 

label_encoder=LabelEncoder()
data['Gender']=label_encoder.fit_transform(data['Gender'])

In [45]:
## One-hot encode 'Geography' column

one_hot_encoded_geo=OneHotEncoder(handle_unknown='ignore')

geo_encoded=one_hot_encoded_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoded_geo.get_feature_names_out(['Geography']))

In [46]:
geo_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [47]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [48]:
## split the data into featuers and target 
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [49]:
## split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


## scale the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [50]:
## Save the encoders and scaler for future use
with open('reg_label_encoder.pkl','wb') as f:
    pickle.dump(label_encoder,f)

with open('reg_one_hot_encoder.pkl','wb') as f:
    pickle.dump(one_hot_encoded_geo,f)

with open('reg_scaler.pkl','wb') as f: 
    pickle.dump(scaler,f)

## ANN Regression Problem Statement

In this project, we are building an Artificial Neural Network (ANN) to predict salary based on various features such as age, experience, education level, and other relevant attributes. The dataset contains numerical and categorical features that need to be preprocessed before feeding into the neural network. The goal is to train a regression model that can accurately predict continuous salary values from these input features.

In [51]:
import tensorflow as tf
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [52]:
## Build the model 

model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])


## compile the model 
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mae'])

In [53]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 64)                832

 dense_13 (Dense)            (None, 32)                2080

 dense_14 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [54]:
from tensorflow.keras.callbacks import EarlyStopping ,TensorBoard

import datetime

## setup tensorboard 
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callbackk=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [56]:
## Setup Early stopping 

early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,
restore_best_weights=True)

In [57]:
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[early_stopping_callback,tensorboard_callbackk])

Epoch 1/100
250/250 [==============================] - 0s 564us/step - loss: 13384301568.0000 - mae: 100381.0938 - val_loss: 13010304000.0000 - val_mae: 98534.0703
Epoch 2/100
250/250 [==============================] - 0s 582us/step - loss: 13244028928.0000 - mae: 99681.3359 - val_loss: 12727604224.0000 - val_mae: 97101.3359
Epoch 3/100
250/250 [==============================] - 0s 409us/step - loss: 12730014720.0000 - mae: 97142.3672 - val_loss: 11983501312.0000 - val_mae: 93328.0234
Epoch 4/100
250/250 [==============================] - 0s 413us/step - loss: 11700215808.0000 - mae: 92036.5625 - val_loss: 10722291712.0000 - val_mae: 86955.7266
Epoch 5/100
250/250 [==============================] - 0s 419us/step - loss: 10184923136.0000 - mae: 84517.4141 - val_loss: 9071962112.0000 - val_mae: 78609.3047
Epoch 6/100
250/250 [==============================] - 0s 434us/step - loss: 8391267328.0000 - mae: 75525.5938 - val_loss: 7299918848.0000 - val_mae: 69727.8750
Epoch 7/100
250/250 [==============================] - 0s 434us/step - loss: 6629668864.0000 - mae: 66632.3281 - val_loss: 5724999680.0000 - val_mae: 61911.6484
Epoch 8/100
250/250 [==============================] - 0s 433us/step - loss: 5199988736.0000 - mae: 59291.9531 - val_loss: 4596708352.0000 - val_mae: 56180.2461
Epoch 9/100
250/250 [==============================] - 0s 441us/step - loss: 4257046784.0000 - mae: 54449.7578 - val_loss: 3947604736.0000 - val_mae: 52940.1016
Epoch 10/100
250/250 [==============================] - 0s 430us/step - loss: 3763473664.0000 - mae: 51847.9297 - val_loss: 3665728256.0000 - val_mae: 51612.8398
Epoch 11/100
250/250 [==============================] - 0s 446us/step - loss: 3553890816.0000 - mae: 50766.9375 - val_loss: 3562196480.0000 - val_mae: 51140.7344
Epoch 12/100
250/250 [==============================] - 0s 414us/step - loss: 3473953024.0000 - mae: 50383.2070 - val_loss: 3524427008.0000 - val_mae: 50941.5078
Epoch 13/100
250/250 [==============================] - 0s 432us/step - loss: 3439378944.0000 - mae: 50221.7266 - val_loss: 3504062208.0000 - val_mae: 50835.1406
Epoch 14/100
250/250 [==============================] - 0s 443us/step - loss: 3419312896.0000 - mae: 50129.3672 - val_loss: 3489325056.0000 - val_mae: 50766.9258
Epoch 15/100
250/250 [==============================] - 0s 459us/step - loss: 3405120000.0000 - mae: 50054.7344 - val_loss: 3475454976.0000 - val_mae: 50694.9023
Epoch 16/100
250/250 [==============================] - 0s 424us/step - loss: 3393166592.0000 - mae: 49991.7617 - val_loss: 3463555072.0000 - val_mae: 50638.6133
Epoch 17/100
250/250 [==============================] - 0s 411us/step - loss: 3382930688.0000 - mae: 49941.9336 - val_loss: 3452512000.0000 - val_mae: 50587.5352
Epoch 18/100
250/250 [==============================] - 0s 427us/step - loss: 3374001408.0000 - mae: 49893.7344 - val_loss: 3443410944.0000 - val_mae: 50547.5156
Epoch 19/100
250/250 [==============================] - 0s 431us/step - loss: 3366495744.0000 - mae: 49856.4922 - val_loss: 3434091520.0000 - val_mae: 50502.0352
Epoch 20/100
250/250 [==============================] - 0s 435us/step - loss: 3359609600.0000 - mae: 49817.7422 - val_loss: 3426817792.0000 - val_mae: 50466.6406
Epoch 21/100
250/250 [==============================] - 0s 416us/step - loss: 3353627392.0000 - mae: 49795.3906 - val_loss: 3419998976.0000 - val_mae: 50436.6797
Epoch 22/100
250/250 [==============================] - 0s 410us/step - loss: 3347954176.0000 - mae: 49761.1445 - val_loss: 3414691328.0000 - val_mae: 50411.8281
Epoch 23/100
250/250 [==============================] - 0s 407us/step - loss: 3343473408.0000 - mae: 49742.2969 - val_loss: 3408751616.0000 - val_mae: 50381.7930
Epoch 24/100
250/250 [==============================] - 0s 405us/step - loss: 3339510528.0000 - mae: 49716.6406 - val_loss: 3403942656.0000 - val_mae: 50359.3594
Epoch 25/100
250/250 [==============================] - 0s 426us/step - loss: 3335435008.0000 - mae: 49697.7578 - val_loss: 3399523072.0000 - val_mae: 50340.4492
Epoch 26/100
250/250 [==============================] - 0s 427us/step - loss: 3332715520.0000 - mae: 49682.1992 - val_loss: 3395409664.0000 - val_mae: 50323.1641
Epoch 27/100
250/250 [==============================] - 0s 407us/step - loss: 3329207808.0000 - mae: 49662.7148 - val_loss: 3393601024.0000 - val_mae: 50313.1992
Epoch 28/100
250/250 [==============================] - 0s 406us/step - loss: 3326701312.0000 - mae: 49651.7266 - val_loss: 3389098240.0000 - val_mae: 50290.2109
Epoch 29/100
250/250 [==============================] - 0s 408us/step - loss: 3324241664.0000 - mae: 49638.7891 - val_loss: 3385520896.0000 - val_mae: 50274.2461
Epoch 30/100
250/250 [==============================] - 0s 431us/step - loss: 3321718784.0000 - mae: 49623.0430 - val_loss: 3384112128.0000 - val_mae: 50268.5352
Epoch 31/100
250/250 [==============================] - 0s 434us/step - loss: 3320044544.0000 - mae: 49614.4141 - val_loss: 3381777152.0000 - val_mae: 50256.8008
Epoch 32/100
250/250 [==============================] - 0s 399us/step - loss: 3317823488.0000 - mae: 49601.2734 - val_loss: 3378629120.0000 - val_mae: 50242.5391
Epoch 33/100
250/250 [==============================] - 0s 404us/step - loss: 3316643584.0000 - mae: 49594.2656 - val_loss: 3379156480.0000 - val_mae: 50250.3242
Epoch 34/100
250/250 [==============================] - 0s 398us/step - loss: 3315093504.0000 - mae: 49589.9297 - val_loss: 3377780224.0000 - val_mae: 50244.0781
Epoch 35/100
250/250 [==============================] - 0s 397us/step - loss: 3313298944.0000 - mae: 49574.0664 - val_loss: 3376467968.0000 - val_mae: 50240.3984
Epoch 36/100
250/250 [==============================] - 0s 397us/step - loss: 3312088832.0000 - mae: 49564.3164 - val_loss: 3373793280.0000 - val_mae: 50223.3633
Epoch 37/100
250/250 [==============================] - 0s 401us/step - loss: 3310411264.0000 - mae: 49554.6602 - val_loss: 3373121792.0000 - val_mae: 50222.4961
Epoch 38/100
250/250 [==============================] - 0s 397us/step - loss: 3309472256.0000 - mae: 49551.3281 - val_loss: 3372149248.0000 - val_mae: 50218.6719
Epoch 39/100
250/250 [==============================] - 0s 396us/step - loss: 3308398080.0000 - mae: 49546.4805 - val_loss: 3369690624.0000 - val_mae: 50204.9922
Epoch 40/100
250/250 [==============================] - 0s 397us/step - loss: 3307607808.0000 - mae: 49539.8516 - val_loss: 3368233728.0000 - val_mae: 50196.4258
Epoch 41/100
250/250 [==============================] - 0s 412us/step - loss: 3306511104.0000 - mae: 49533.0117 - val_loss: 3369321216.0000 - val_mae: 50206.9023
Epoch 42/100
250/250 [==============================] - 0s 425us/step - loss: 3305282816.0000 - mae: 49523.3281 - val_loss: 3366713344.0000 - val_mae: 50189.8594
Epoch 43/100
250/250 [==============================] - 0s 402us/step - loss: 3304468992.0000 - mae: 49527.4219 - val_loss: 3365256192.0000 - val_mae: 50179.0312
Epoch 44/100
250/250 [==============================] - 0s 399us/step - loss: 3303873792.0000 - mae: 49516.5273 - val_loss: 3365329408.0000 - val_mae: 50181.7773
Epoch 45/100
250/250 [==============================] - 0s 401us/step - loss: 3302949376.0000 - mae: 49511.7773 - val_loss: 3363905792.0000 - val_mae: 50173.6953
Epoch 46/100
250/250 [==============================] - 0s 398us/step - loss: 3302449152.0000 - mae: 49507.7461 - val_loss: 3364423680.0000 - val_mae: 50179.3984
Epoch 47/100
250/250 [==============================] - 0s 397us/step - loss: 3301642496.0000 - mae: 49500.6406 - val_loss: 3363632896.0000 - val_mae: 50175.0898
Epoch 48/100
250/250 [==============================] - 0s 402us/step - loss: 3300506880.0000 - mae: 49495.0000 - val_loss: 3363656448.0000 - val_mae: 50176.3984
Epoch 49/100
250/250 [==============================] - 0s 414us/step - loss: 3300169984.0000 - mae: 49494.2109 - val_loss: 3363037184.0000 - val_mae: 50172.3008
Epoch 50/100
250/250 [==============================] - 0s 402us/step - loss: 3299461376.0000 - mae: 49489.1836 - val_loss: 3361240320.0000 - val_mae: 50158.6641
Epoch 51/100
250/250 [==============================] - 0s 399us/step - loss: 3298995712.0000 - mae: 49485.6523 - val_loss: 3361459712.0000 - val_mae: 50160.2109
Epoch 52/100
250/250 [==============================] - 0s 412us/step - loss: 3298260480.0000 - mae: 49476.1836 - val_loss: 3363474688.0000 - val_mae: 50174.9453
Epoch 53/100
250/250 [==============================] - 0s 408us/step - loss: 3298148608.0000 - mae: 49483.8672 - val_loss: 3361097472.0000 - val_mae: 50158.6562
Epoch 54/100
250/250 [==============================] - 0s 400us/step - loss: 3296986624.0000 - mae: 49473.6016 - val_loss: 3361793280.0000 - val_mae: 50164.8828
Epoch 55/100
250/250 [==============================] - 0s 405us/step - loss: 3296488960.0000 - mae: 49466.6680 - val_loss: 3362703616.0000 - val_mae: 50171.6289
Epoch 56/100
250/250 [==============================] - 0s 399us/step - loss: 3295907328.0000 - mae: 49462.5195 - val_loss: 3362441728.0000 - val_mae: 50168.5195
Epoch 57/100
250/250 [==============================] - 0s 400us/step - loss: 3295758336.0000 - mae: 49465.5586 - val_loss: 3362272000.0000 - val_mae: 50167.3203
Epoch 58/100
250/250 [==============================] - 0s 399us/step - loss: 3295247872.0000 - mae: 49456.3672 - val_loss: 3361640448.0000 - val_mae: 50164.5859
Epoch 59/100
250/250 [==============================] - 0s 400us/step - loss: 3294410496.0000 - mae: 49455.9492 - val_loss: 3362762496.0000 - val_mae: 50169.6484
Epoch 60/100
250/250 [==============================] - 0s 400us/step - loss: 3294120448.0000 - mae: 49448.2539 - val_loss: 3360911104.0000 - val_mae: 50159.4531
Epoch 61/100
250/250 [==============================] - 0s 400us/step - loss: 3293534464.0000 - mae: 49446.0898 - val_loss: 3361569536.0000 - val_mae: 50164.9844
Epoch 62/100
250/250 [==============================] - 0s 400us/step - loss: 3293227520.0000 - mae: 49442.0234 - val_loss: 3362452736.0000 - val_mae: 50172.6055
Epoch 63/100
250/250 [==============================] - 0s 397us/step - loss: 3292359680.0000 - mae: 49441.5742 - val_loss: 3359920128.0000 - val_mae: 50153.9258
Epoch 64/100
250/250 [==============================] - 0s 392us/step - loss: 3291845376.0000 - mae: 49430.7812 - val_loss: 3361341440.0000 - val_mae: 50163.3711
Epoch 65/100
250/250 [==============================] - 0s 398us/step - loss: 3292095744.0000 - mae: 49438.6094 - val_loss: 3360223488.0000 - val_mae: 50154.5039
Epoch 66/100
250/250 [==============================] - 0s 396us/step - loss: 3291163392.0000 - mae: 49429.4023 - val_loss: 3358824960.0000 - val_mae: 50143.7227
Epoch 67/100
250/250 [==============================] - 0s 400us/step - loss: 3290999808.0000 - mae: 49427.1055 - val_loss: 3359114496.0000 - val_mae: 50145.4062
Epoch 68/100
250/250 [==============================] - 0s 397us/step - loss: 3290682112.0000 - mae: 49426.4141 - val_loss: 3359005952.0000 - val_mae: 50145.7344
Epoch 69/100
250/250 [==============================] - 0s 395us/step - loss: 3290170624.0000 - mae: 49423.1758 - val_loss: 3358828288.0000 - val_mae: 50145.9141
Epoch 70/100
250/250 [==============================] - 0s 398us/step - loss: 3289708544.0000 - mae: 49419.6016 - val_loss: 3359598080.0000 - val_mae: 50149.8828
Epoch 71/100
250/250 [==============================] - 0s 395us/step - loss: 3289438208.0000 - mae: 49418.8789 - val_loss: 3358904832.0000 - val_mae: 50145.4492
Epoch 72/100
250/250 [==============================] - 0s 398us/step - loss: 3289148672.0000 - mae: 49413.4570 - val_loss: 3357880064.0000 - val_mae: 50136.3789
Epoch 73/100
250/250 [==============================] - 0s 399us/step - loss: 3288697856.0000 - mae: 49412.0312 - val_loss: 3357877504.0000 - val_mae: 50138.0273
Epoch 74/100
250/250 [==============================] - 0s 396us/step - loss: 3288256512.0000 - mae: 49413.9453 - val_loss: 3357805056.0000 - val_mae: 50136.6133
Epoch 75/100
250/250 [==============================] - 0s 404us/step - loss: 3287764480.0000 - mae: 49406.8398 - val_loss: 3358738176.0000 - val_mae: 50143.1602
Epoch 76/100
250/250 [==============================] - 0s 615us/step - loss: 3287644928.0000 - mae: 49400.9258 - val_loss: 3358466048.0000 - val_mae: 50139.7578
Epoch 77/100
250/250 [==============================] - 0s 975us/step - loss: 3287293696.0000 - mae: 49401.6445 - val_loss: 3358054912.0000 - val_mae: 50136.9219
Epoch 78/100
250/250 [==============================] - 0s 738us/step - loss: 3286752256.0000 - mae: 49398.0430 - val_loss: 3358570752.0000 - val_mae: 50140.7656
Epoch 79/100
250/250 [==============================] - 0s 496us/step - loss: 3286929408.0000 - mae: 49401.6992 - val_loss: 3359204352.0000 - val_mae: 50145.0273
Epoch 80/100
250/250 [==============================] - 0s 441us/step - loss: 3286315264.0000 - mae: 49396.6680 - val_loss: 3359333120.0000 - val_mae: 50148.3477
Epoch 81/100
250/250 [==============================] - 0s 433us/step - loss: 3285984512.0000 - mae: 49392.5273 - val_loss: 3358127360.0000 - val_mae: 50138.2852
Epoch 82/100
250/250 [==============================] - 0s 425us/step - loss: 3285734912.0000 - mae: 49387.3281 - val_loss: 3357393664.0000 - val_mae: 50131.7695
Epoch 83/100
250/250 [==============================] - 0s 409us/step - loss: 3285181440.0000 - mae: 49385.8984 - val_loss: 3357866496.0000 - val_mae: 50135.0391
Epoch 84/100
250/250 [==============================] - 0s 417us/step - loss: 3285386752.0000 - mae: 49381.6484 - val_loss: 3358661376.0000 - val_mae: 50141.2617
Epoch 85/100
250/250 [==============================] - 0s 426us/step - loss: 3284350208.0000 - mae: 49379.0742 - val_loss: 3358271744.0000 - val_mae: 50138.3984
Epoch 86/100
250/250 [==============================] - 0s 429us/step - loss: 3284471552.0000 - mae: 49379.7070 - val_loss: 3358086144.0000 - val_mae: 50136.3359
Epoch 87/100
250/250 [==============================] - 0s 412us/step - loss: 3284271360.0000 - mae: 49386.7617 - val_loss: 3358702080.0000 - val_mae: 50140.6953
Epoch 88/100
250/250 [==============================] - 0s 408us/step - loss: 3283654400.0000 - mae: 49381.0859 - val_loss: 3357548544.0000 - val_mae: 50132.6641
Epoch 89/100
250/250 [==============================] - 0s 408us/step - loss: 3283497216.0000 - mae: 49373.1289 - val_loss: 3358873088.0000 - val_mae: 50140.4102
Epoch 90/100
250/250 [==============================] - 0s 408us/step - loss: 3283373824.0000 - mae: 49376.2305 - val_loss: 3357905408.0000 - val_mae: 50134.4219
Epoch 91/100
250/250 [==============================] - 0s 419us/step - loss: 3283273984.0000 - mae: 49372.6914 - val_loss: 3358365952.0000 - val_mae: 50136.3984
Epoch 92/100
250/250 [==============================] - 0s 430us/step - loss: 3282847232.0000 - mae: 49367.1250 - val_loss: 3358823936.0000 - val_mae: 50142.8555

In [32]:
%load_ext tensorboard

In [35]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6007 (pid 5614), started 0:03:50 ago. (Use '!kill 5614' to kill it.)

In [37]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

63/63 [==============================] - 0s 235us/step - loss: 3354891776.0000 - mae: 50094.4805
Test Loss: 3354891776.0, Test MAE: 50094.48046875

In [38]:
model.save('regression_model.h5')

/Users/anupdangi/Desktop/AnupAI/Research/DS_ML_DL_NLP_BOOTCAMP/venv/lib/python3.9/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0